## **Learning PyTorch**

**Scaler Vector and Tensor**

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.7.1+cpu


*Scalers*

In [5]:
#scaler
scaler = torch.tensor(7)
scaler

tensor(7)

In [7]:
scaler.ndim

7

In [49]:
scaler.item()

7

*Vectors*

In [8]:
#Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

*Tensors*

In [11]:
#MATRIX
MATRIX = torch.tensor([[7,8],
                       [1,2]])
MATRIX

tensor([[7, 8],
        [1, 2]])

In [13]:
MATRIX.ndim

2

In [14]:
MATRIX[1]


tensor([1, 2])

In [33]:
#TENSOR
tensor = torch.tensor([[1,2,3],
                       [0,2,2],
                       [2,2,1]])
tensor

tensor([[1, 2, 3],
        [0, 2, 2],
        [2, 2, 1]])

In [35]:
tensor.ndim

2

In [38]:
tensor[0]

tensor([1, 2, 3])

In [37]:
tensor[1]

tensor([0, 2, 2])

In [44]:
tensor.shape

torch.Size([3, 3])

In [10]:
tensor2 = torch.tensor([[[1,2,3],
                         [0,2,2],
                         [2,2,1]]])
tensor2

tensor([[[1, 2, 3],
         [0, 2, 2],
         [2, 2, 1]]])

In [6]:
tensor2.ndim

3

In [7]:
tensor2.shape

torch.Size([1, 3, 3])

In [46]:
tensor2[0]

tensor([[1, 2, 3],
        [0, 2, 2],
        [2, 2, 1]])

# **Generating tensors**

In [29]:
import torch
TT = torch.rand([3,3,2], out=None, dtype=None, 
                layout=torch.strided, device=None, requires_grad=False)
print(TT)

tensor([[[0.5264, 0.1557],
         [0.9003, 0.7315],
         [0.2184, 0.3087]],

        [[0.6412, 0.4854],
         [0.4994, 0.2307],
         [0.4467, 0.3222]],

        [[0.6528, 0.2824],
         [0.5511, 0.8943],
         [0.1262, 0.5909]]])


In [30]:
TT.ndim

3

In [31]:
TT.shape

torch.Size([3, 3, 2])

In [35]:
TT.dtype

torch.float32

In [32]:
TT[0]

tensor([[0.5264, 0.1557],
        [0.9003, 0.7315],
        [0.2184, 0.3087]])

In [33]:
TT[1]

tensor([[0.6412, 0.4854],
        [0.4994, 0.2307],
        [0.4467, 0.3222]])

In [34]:
TT[2]

tensor([[0.6528, 0.2824],
        [0.5511, 0.8943],
        [0.1262, 0.5909]])

In [24]:
import torch
x=torch.rand(8)
print(x.size())
x=x.view(2,2,2)
print(x.size())
print(x)

torch.Size([8])
torch.Size([2, 2, 2])
tensor([[[0.1739, 0.0715],
         [0.7655, 0.9047]],

        [[0.9304, 0.7610],
         [0.9177, 0.3957]]])


In [37]:
import torch
TT = torch.rand([3,3,2], out=None, dtype=torch.float16, 
                layout=torch.strided, device=None, requires_grad=False)
print(TT)

tensor([[[0.0728, 0.6309],
         [0.8057, 0.6729],
         [0.6885, 0.3975]],

        [[0.1118, 0.5029],
         [0.8721, 0.6802],
         [0.6104, 0.8008]],

        [[0.8877, 0.5874],
         [0.8789, 0.0923],
         [0.2808, 0.7202]]], dtype=torch.float16)


In [38]:
TT.dtype

torch.float16